sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-26.0.2
    - android-26

script: cd Clover && ./gradlew build --console plain -x lint
