sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-25.0.0
    - android-25

script: cd Clover && ./gradlew build --console plain -x lint
